/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import static form.Loading.i;
import form.siswa.Profile;
import form.siswa.CekNilai;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author resar
 */
public class DashboardSiswa extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    Color DefaultColor, ClickedColor, LogoutColor;
    String nis;
    Utility Utility = new Utility();
    public DashboardSiswa(String nis) throws InterruptedException {
        this.nis = nis;
        initComponents();
        DefaultColor = new Color(128,208,255);
        ClickedColor=new Color(255,223,93);
        LogoutColor = new Color(244,67,54);
//        Default Color
        jpProfile.setBackground(ClickedColor);
        jpCekNilai.setBackground(DefaultColor);
        jpPengaturan.setBackground(DefaultColor);
        jpLogout.setBackground(DefaultColor);
        
        Profile Profile = new Profile(nis);
        DesktopPanel.removeAll();
        DesktopPanel.add(Profile).setVisible(true);
        ShowPesan();
    }
    
    public void ShowPesan() throws InterruptedException{
        String[] pesan = Utility.ShowInfo();
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                for(i=0; i<pesan.length; i++){
                    try{
                        lblPesanInfo.setText(pesan[i]);
                        Thread.sleep(5000);
                    } 
                    catch(InterruptedException ex){
                        Logger.getLogger(DashboardSiswa.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                try {
                    ShowPesan();
                } catch (InterruptedException ex) {
                    Logger.getLogger(DashboardSiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jpCekNilai = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpProfile = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpLogout = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jpPengaturan = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jpJudul = new javax.swing.JPanel();
        NamaMenu = new javax.swing.JLabel();
        Breadcrumb = new javax.swing.JLabel();
        DesktopPanel = new javax.swing.JPanel();
        jpInfoPesan = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        lblPesanInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(2, 162, 255));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpCekNilai.setBackground(new java.awt.Color(128, 208, 255));
        jpCekNilai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpCekNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpCekNilaiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpCekNilaiMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CEK NILAI");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cek_nilai.png"))); // NOI18N

        javax.swing.GroupLayout jpCekNilaiLayout = new javax.swing.GroupLayout(jpCekNilai);
        jpCekNilai.setLayout(jpCekNilaiLayout);
        jpCekNilaiLayout.setHorizontalGroup(
            jpCekNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCekNilaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpCekNilaiLayout.setVerticalGroup(
            jpCekNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCekNilaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpCekNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(jpCekNilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 270, 50));

        jpProfile.setBackground(new java.awt.Color(128, 208, 255));
        jpProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpProfileMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpProfileMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PROFILE");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile.png"))); // NOI18N

        javax.swing.GroupLayout jpProfileLayout = new javax.swing.GroupLayout(jpProfile);
        jpProfile.setLayout(jpProfileLayout);
        jpProfileLayout.setHorizontalGroup(
            jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpProfileLayout.setVerticalGroup(
            jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(jpProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 50));

        jpLogout.setBackground(new java.awt.Color(128, 208, 255));
        jpLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpLogoutMousePressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("LOGOUT");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N

        javax.swing.GroupLayout jpLogoutLayout = new javax.swing.GroupLayout(jpLogout);
        jpLogout.setLayout(jpLogoutLayout);
        jpLogoutLayout.setHorizontalGroup(
            jpLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpLogoutLayout.setVerticalGroup(
            jpLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(jpLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 270, 50));

        jpPengaturan.setBackground(new java.awt.Color(128, 208, 255));
        jpPengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpPengaturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpPengaturanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpPengaturanMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PENGATURAN");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pengaturan.png"))); // NOI18N

        javax.swing.GroupLayout jpPengaturanLayout = new javax.swing.GroupLayout(jpPengaturan);
        jpPengaturan.setLayout(jpPengaturanLayout);
        jpPengaturanLayout.setHorizontalGroup(
            jpPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPengaturanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpPengaturanLayout.setVerticalGroup(
            jpPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPengaturanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(jpPengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 50));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-80.png"))); // NOI18N
        sidePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, 90));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SISWA");
        sidePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 100, -1, -1));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 600));

        jpJudul.setBackground(new java.awt.Color(31, 185, 242));

        NamaMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NamaMenu.setForeground(new java.awt.Color(255, 255, 255));
        NamaMenu.setText("PROFILE________________________________________________");

        Breadcrumb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Breadcrumb.setForeground(new java.awt.Color(255, 255, 255));
        Breadcrumb.setText("SISWA/PROFLE");

        javax.swing.GroupLayout jpJudulLayout = new javax.swing.GroupLayout(jpJudul);
        jpJudul.setLayout(jpJudulLayout);
        jpJudulLayout.setHorizontalGroup(
            jpJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpJudulLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaMenu)
                    .addComponent(Breadcrumb))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jpJudulLayout.setVerticalGroup(
            jpJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpJudulLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Breadcrumb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(NamaMenu)
                .addContainerGap())
        );

        bg.add(jpJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 60, 740, -1));

        DesktopPanel.setLayout(new javax.swing.BoxLayout(DesktopPanel, javax.swing.BoxLayout.LINE_AXIS));
        bg.add(DesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 740, 420));

        jpInfoPesan.setBackground(new java.awt.Color(41, 166, 75));
        jpInfoPesan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo.setText("INFO:");
        jpInfoPesan.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, -1, -1));

        lblPesanInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPesanInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblPesanInfo.setAlignmentY(2.0F);
        jpInfoPesan.add(lblPesanInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, 661, -1));

        bg.add(jpInfoPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 0, 740, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpProfileMousePressed
        jpProfile.setBackground(ClickedColor);
        jpCekNilai.setBackground(DefaultColor);
        jpPengaturan.setBackground(DefaultColor);
        jpLogout.setBackground(DefaultColor);

        NamaMenu.setText("HALAMAN PROFILE________________________________________");
        Breadcrumb.setText("SISWA/PROFILE");
    }//GEN-LAST:event_jpProfileMousePressed

    private void jpCekNilaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCekNilaiMousePressed
        jpProfile.setBackground(DefaultColor);
        jpCekNilai.setBackground(ClickedColor);
        jpPengaturan.setBackground(DefaultColor);
        jpLogout.setBackground(DefaultColor);
        NamaMenu.setText("HALAMAN CEK NILAI_______________________________________");
        Breadcrumb.setText("SISWA/ISINILAI");
    }//GEN-LAST:event_jpCekNilaiMousePressed

    private void jpLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLogoutMousePressed
        jpProfile.setBackground(DefaultColor);
        jpCekNilai.setBackground(DefaultColor);
        jpPengaturan.setBackground(DefaultColor);
        jpLogout.setBackground(LogoutColor);
    }//GEN-LAST:event_jpLogoutMousePressed

    private void jpProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpProfileMouseClicked
        Profile Profile = new Profile(nis);
        DesktopPanel.removeAll();
        DesktopPanel.add(Profile).setVisible(true);
    }//GEN-LAST:event_jpProfileMouseClicked

    private void jpCekNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCekNilaiMouseClicked
        CekNilai CekNilai = new CekNilai(nis);
        DesktopPanel.removeAll();
        DesktopPanel.add(CekNilai).setVisible(true);
    }//GEN-LAST:event_jpCekNilaiMouseClicked

    private void jpLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLogoutMouseClicked
        // TODO add your handling code here:
        int conf;
            conf = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Keluar?",
                    "Warning",JOptionPane.WARNING_MESSAGE);
            if(conf == 0){
                this.dispose();
                Login Login = new Login();
                Login.setVisible(true);
            } else{
                jpLogout.setBackground(DefaultColor);
            }

    }//GEN-LAST:event_jpLogoutMouseClicked

    private void jpPengaturanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPengaturanMouseClicked
        Pengaturan Pengaturan = new Pengaturan(nis, 2);
        DesktopPanel.removeAll();
        DesktopPanel.add(Pengaturan).setVisible(true);
    }//GEN-LAST:event_jpPengaturanMouseClicked

    private void jpPengaturanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPengaturanMousePressed
        jpProfile.setBackground(DefaultColor);
        jpCekNilai.setBackground(DefaultColor);
        jpPengaturan.setBackground(ClickedColor);
        jpLogout.setBackground(DefaultColor);
        NamaMenu.setText("HALAMAN PENGATURAN_____________________________________");
        Breadcrumb.setText("SISWA/PENGATURAN");
    }//GEN-LAST:event_jpPengaturanMousePressed

    /**
     * @param args the command line arguments
     */                                                                                                                                                                                                         
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Breadcrumb;
    private javax.swing.JPanel DesktopPanel;
    private javax.swing.JLabel NamaMenu;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jpCekNilai;
    private javax.swing.JPanel jpInfoPesan;
    private javax.swing.JPanel jpJudul;
    private javax.swing.JPanel jpLogout;
    private javax.swing.JPanel jpPengaturan;
    private javax.swing.JPanel jpProfile;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblPesanInfo;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
