/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import database.KoneksiDB;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author resar
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }
    PreparedStatement ps = null;
    ResultSet Rs = null, Rs1 = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        IconLogo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        IconPassword = new javax.swing.JLabel();
        IconUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(2, 162, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setText("SMA");
        jPanel2.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 190, 110, -1));

        IconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-160.png"))); // NOI18N
        jPanel2.add(IconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 370));

        jPanel3.setBackground(new java.awt.Color(2, 155, 238));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        lblPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPasswordMousePressed(evt);
            }
        });
        jPanel3.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 220, -1));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUsernameMousePressed(evt);
            }
        });
        jPanel3.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 220, -1));

        tfUsername.setBackground(new java.awt.Color(2, 155, 238));
        tfUsername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(255, 255, 255));
        tfUsername.setToolTipText("");
        tfUsername.setBorder(null);
        tfUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        tfUsername.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        tfUsername.setEnabled(false);
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        tfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUsernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfUsernameKeyReleased(evt);
            }
        });
        jPanel3.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 220, -1));

        pfPassword.setBackground(new java.awt.Color(2, 155, 238));
        pfPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pfPassword.setForeground(new java.awt.Color(255, 255, 255));
        pfPassword.setToolTipText("");
        pfPassword.setBorder(null);
        pfPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        pfPassword.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        pfPassword.setEnabled(false);
        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });
        pfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pfPasswordKeyReleased(evt);
            }
        });
        jPanel3.add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 220, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 220, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 220, 10));

        jPanel4.setBackground(new java.awt.Color(2, 155, 238));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel4.setToolTipText("");
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setFocusable(false);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnLoginKeyReleased(evt);
            }
        });
        jPanel4.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -7, 200, 50));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 190, 40));

        IconPassword.setToolTipText("");
        jPanel3.add(IconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        IconUsername.setToolTipText("");
        jPanel3.add(IconUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 360, 370));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblUsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMousePressed
        // TODO add your handling code here:
        lblUsername.setVisible(false);
        tfUsername.setEnabled(true);
    }//GEN-LAST:event_lblUsernameMousePressed

    private void lblPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPasswordMousePressed
        // TODO add your handling code here:
        lblPassword.setVisible(false);
        pfPassword.setEnabled(true);
    }//GEN-LAST:event_lblPasswordMousePressed
    
    private void LoginAction() throws InterruptedException{
        try{
            KoneksiDB k = new KoneksiDB();
            Connection con = k.connection;
        Statement St=con.createStatement();
        String Query = "SELECT * FROM user WHERE username='"+tfUsername.getText()+"' AND password='"+ Utility.getMd5(pfPassword.getText())+"'";
            Rs = St.executeQuery(Query);
            if(Rs.next()){
                if(tfUsername.getText().equals(Rs.getString("username")) && Utility.getMd5(pfPassword.getText()).equals(Rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Login Berhasil!");
                    setVisible(false);
                    if(Rs.getInt("role") == 1){
                        new DashboardAdmin().setVisible(true);
                    } else if(Rs.getInt("role") == 2){
                        new DashboardGuru(Rs.getString("username")).setVisible(true);
                    } else if(Rs.getInt("role") == 3){
                        new DashboardSiswa(Rs.getString("username")).setVisible(true);
                    }
                    this.dispose();
                }
            }else{
                    JOptionPane.showMessageDialog(null, "Username Atau Password Salah");
                }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        try {
            // TODO add your handling code here:
            LoginAction();
        } catch (InterruptedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                LoginAction();
            } catch (InterruptedException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLoginKeyReleased

    private void tfUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsernameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                LoginAction();
            } catch (InterruptedException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tfUsernameKeyPressed

    private void pfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                LoginAction();
            } catch (InterruptedException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_pfPasswordKeyPressed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
        lblUsername.setVisible(false);
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void tfUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsernameKeyReleased
        // TODO add your handling code here:
        lblUsername.setVisible(false);
        if(tfUsername.getText().isEmpty()){
            lblUsername.setVisible(true);
        }
    }//GEN-LAST:event_tfUsernameKeyReleased

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
        lblPassword.setVisible(false);
    }//GEN-LAST:event_pfPasswordActionPerformed

    private void pfPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPasswordKeyReleased
       lblPassword.setVisible(false);
        if(pfPassword.getText().isEmpty()){
            lblPassword.setVisible(true);
        }
    }//GEN-LAST:event_pfPasswordKeyReleased

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconLogo;
    private javax.swing.JLabel IconPassword;
    private javax.swing.JLabel IconUsername;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
