/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package form;

import database.KoneksiDB;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author resar
 */
public class Pengaturan extends javax.swing.JInternalFrame {

    /**
     * Creates new form Profile
     */
    KoneksiDB k = new KoneksiDB();
    Connection con = k.connection;
    String id;
    int role;
    public Pengaturan(String id, int role) {
        this.id = id;
        this.role = role;
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUbahPassword = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnBantuan = new javax.swing.JButton();
        btnUbahGambar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(560, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pengaturanx2.png"))); // NOI18N

        btnUbahPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUbahPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ubahpassword.png"))); // NOI18N
        btnUbahPassword.setText("UBAH PASSWORD");
        btnUbahPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbahPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbahPasswordMouseClicked(evt);
            }
        });

        btnInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/infoapp.png"))); // NOI18N
        btnInfo.setText("INFO APLIKASI");
        btnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInfoMouseClicked(evt);
            }
        });

        btnBantuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBantuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bantuan.png"))); // NOI18N
        btnBantuan.setText("BANTUAN");
        btnBantuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBantuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBantuanMouseClicked(evt);
            }
        });

        btnUbahGambar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUbahGambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ubahgambar.png"))); // NOI18N
        btnUbahGambar.setText("UBAH GAMBAR");
        btnUbahGambar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbahGambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbahGambarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBantuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUbahPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(btnUbahGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbahPassword)
                    .addComponent(btnUbahGambar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBantuan)
                    .addComponent(btnInfo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahPasswordMouseClicked
        new UbahPassword(id).setVisible(true);
    }//GEN-LAST:event_btnUbahPasswordMouseClicked

    private void btnInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseClicked
        JOptionPane.showMessageDialog(this, "Aplikasi Ini Dikembangkan Oleh Personal!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnInfoMouseClicked

    private void btnBantuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBantuanMouseClicked
       JOptionPane.showMessageDialog(this, "Hubungi Admin Jika Terdapat Masalah/Error Pada Aplikasi", "Bantuan", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnBantuanMouseClicked

    private void btnUbahGambarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahGambarMouseClicked
        // TODO add your handling code here:
        new UbahGambar(id, role).setVisible(true);
    }//GEN-LAST:event_btnUbahGambarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBantuan;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnUbahGambar;
    private javax.swing.JButton btnUbahPassword;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
