/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import database.KoneksiDB;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author resar
 */
public class UbahPassword extends javax.swing.JFrame {

    /**
     * Creates new form UbahPassword
     */
    KoneksiDB k = new KoneksiDB();
    Connection con = k.connection;
    String id;
    public UbahPassword(String id) {
        setLocationRelativeTo(null);
        this.id = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        pfPasswordLama = new javax.swing.JPasswordField();
        pfPasswordBaru = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("UBAH PASSWORD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 66, 220, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("PASSWORD LAMA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 143, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("PASSWORD BARU:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 191, -1, -1));

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-making_notes.png"))); // NOI18N
        btnEdit.setText("UBAH PASSWORD");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEditKeyPressed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 230, 222, -1));

        pfPasswordLama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPasswordLamaKeyPressed(evt);
            }
        });
        jPanel1.add(pfPasswordLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 134, 220, 35));

        pfPasswordBaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPasswordBaruKeyPressed(evt);
            }
        });
        jPanel1.add(pfPasswordBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 182, 222, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void UbahPassword(){
        if(pfPasswordLama.getText().trim().isEmpty() || pfPasswordBaru.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Isi Semua Field!");
        } else{
            Statement st;
            ResultSet rs;
            String query = "SELECT * FROM user WHERE username = "+id+" AND password = '"+Utility.getMd5(pfPasswordLama.getText())+"'";
            
            try {
                st = con.createStatement();
                rs = st.executeQuery(query);
                if(rs.next()){
                    query = "UPDATE user SET `password` = '"+ Utility.getMd5(pfPasswordBaru.getText()) +"' WHERE username='"+id+"'";
                    System.out.println(query);
                    try{
                        if(st.executeUpdate(query)>0){
                            boolean conf;
                            JOptionPane.showMessageDialog(null, "Password Berhasil Dirubah!", "Success", JOptionPane.INFORMATION_MESSAGE);
                            this.dispose();
                        } 
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else{
                    JOptionPane.showMessageDialog(this, "Password Gagal Dirubah!", "Error", JOptionPane.ERROR_MESSAGE);
                }
                         
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        UbahPassword();
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEditKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
             this.dispose();
        } else if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            UbahPassword();
        }
    }//GEN-LAST:event_btnEditKeyPressed

    private void pfPasswordBaruKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPasswordBaruKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
             this.dispose();
        }
    }//GEN-LAST:event_pfPasswordBaruKeyPressed

    private void pfPasswordLamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPasswordLamaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
             this.dispose();
        }
    }//GEN-LAST:event_pfPasswordLamaKeyPressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pfPasswordBaru;
    private javax.swing.JPasswordField pfPasswordLama;
    // End of variables declaration//GEN-END:variables
}
