/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package form.admin;

import database.KoneksiDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author resar
 */
public class Dashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dashboard
     */
    KoneksiDB k = new KoneksiDB();
    Connection con = k.connection;
    public Dashboard() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        CekJumlah();
    }
    
    public void CekJumlah(){
        Statement st;
        ResultSet rs;

        String query = "SELECT COUNT(nis) as jumlahSiswa FROM datasiswa";
        try{
            st = con.createStatement();
            rs = st.executeQuery(query);
            if(rs.next()){
                lblJSiswa.setText(rs.getString("jumlahSiswa"));
            }
        }catch (Exception e) {
            e.printStackTrace();
        }
        query = "SELECT COUNT(nip) as jumlahGuru FROM dataguru";
        try{
            st = con.createStatement();
            rs = st.executeQuery(query);
            if(rs.next()){
                lblJGuru.setText(rs.getString("jumlahGuru"));
            }
        }catch (Exception e) {
            e.printStackTrace();
        }
        query = "SELECT COUNT(id_kelas) as jumlahKelas FROM kelas";
        try{
            st = con.createStatement();
            rs = st.executeQuery(query);
            if(rs.next()){
                lblJKelas.setText(rs.getString("jumlahKelas"));
            }
        }catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard = new javax.swing.JPanel();
        jpButtom = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblJSiswa = new javax.swing.JLabel();
        Dashboard1 = new javax.swing.JPanel();
        jpButtom1 = new javax.swing.JPanel();
        lblJudul1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblJGuru = new javax.swing.JLabel();
        Dashboard2 = new javax.swing.JPanel();
        jpButtom2 = new javax.swing.JPanel();
        lblJudul2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblJKelas = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setBackground(new java.awt.Color(2, 162, 255));
        Dashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jpButtom.setBackground(new java.awt.Color(21, 144, 164));
        jpButtom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("SISWA");
        jpButtom.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/studentx100.png"))); // NOI18N

        lblJSiswa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblJSiswa.setForeground(new java.awt.Color(255, 255, 255));
        lblJSiswa.setText("0");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(49, 49, 49))
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lblJSiswa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 210));

        Dashboard1.setBackground(new java.awt.Color(41, 166, 75));
        Dashboard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jpButtom1.setBackground(new java.awt.Color(37, 150, 68));
        jpButtom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudul1.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul1.setText("GURU");
        jpButtom1.add(lblJudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guru100x.png"))); // NOI18N

        lblJGuru.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblJGuru.setForeground(new java.awt.Color(255, 255, 255));
        lblJGuru.setText("0");

        javax.swing.GroupLayout Dashboard1Layout = new javax.swing.GroupLayout(Dashboard1);
        Dashboard1.setLayout(Dashboard1Layout);
        Dashboard1Layout.setHorizontalGroup(
            Dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpButtom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dashboard1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(68, 68, 68))
            .addGroup(Dashboard1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblJGuru)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dashboard1Layout.setVerticalGroup(
            Dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpButtom1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Dashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 40, -1, 210));

        Dashboard2.setBackground(new java.awt.Color(255, 194, 19));
        Dashboard2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jpButtom2.setBackground(new java.awt.Color(228, 173, 14));
        jpButtom2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudul2.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul2.setText("KELAS");
        jpButtom2.add(lblJudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kelas100x.png"))); // NOI18N

        lblJKelas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblJKelas.setForeground(new java.awt.Color(255, 255, 255));
        lblJKelas.setText("0");

        javax.swing.GroupLayout Dashboard2Layout = new javax.swing.GroupLayout(Dashboard2);
        Dashboard2.setLayout(Dashboard2Layout);
        Dashboard2Layout.setHorizontalGroup(
            Dashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(jpButtom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dashboard2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJKelas)
                .addGap(88, 88, 88))
        );
        Dashboard2Layout.setVerticalGroup(
            Dashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpButtom2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Dashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 39, -1, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Dashboard1;
    private javax.swing.JPanel Dashboard2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpButtom;
    private javax.swing.JPanel jpButtom1;
    private javax.swing.JPanel jpButtom2;
    private javax.swing.JLabel lblJGuru;
    private javax.swing.JLabel lblJKelas;
    private javax.swing.JLabel lblJSiswa;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul1;
    private javax.swing.JLabel lblJudul2;
    // End of variables declaration//GEN-END:variables
}
