/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package form.admin;

import database.KoneksiDB;
import form.Utility;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author resar
 */

public class Mapel extends javax.swing.JInternalFrame {

    /**
     * Creates new form Profile
     */
    KoneksiDB k = new KoneksiDB();
    Connection con = k.connection;
    String kodeMatkul = "";
    String namaTabel = "matapelajaran";

    public Mapel() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        showMapel();
        tblMapel.setAutoCreateRowSorter(true);
    }    
    public void showMapel(){
        
        DefaultTableModel model = (DefaultTableModel) tblMapel.getModel();
        
        Statement st;
        ResultSet rs;
        
        String query = "SELECT * FROM matapelajaran";
        String status = null;

        try {
            st = con.createStatement();
            rs = st.executeQuery(query);
            
            Object[] row = new Object[3];
            int no = 0;
            while(rs.next()){
                row[0] = ++no;
                row[1] = rs.getString("kode_matkul");
                row[2] = rs.getString("nama_matkul");
                model.addRow(row);
            }            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void executeSQLQuery(String query, String pesan, int check)
    {
        Statement st;
        ResultSet rs;
        String queryCheck = "call checkKodeMatkul('"+ tfKodeMatkul.getText() +"')";
        
        try{
            st = con.createStatement();
            rs = st.executeQuery(queryCheck);
            if(check == 1){
                if(!rs.next()){
                    if(st.executeUpdate(query)>0){
                        RefreshPage();
                        kodeMatkul="";
                        JOptionPane.showMessageDialog(null, "Data " + pesan+ " Succesfully");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Data Not " + pesan);            
                    }
                } else{
                    JOptionPane.showMessageDialog(null, "Kode Matkul Sudah Tedaftar");
                }
            } else{
                if(st.executeUpdate(query)>0){
                    RefreshPage();
                    kodeMatkul="";
                    JOptionPane.showMessageDialog(null, "Data " + pesan+ " Succesfully");
                } 
                else{
                    JOptionPane.showMessageDialog(null, "Data Not " + pesan);
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void RefreshPage(){
        DefaultTableModel model = (DefaultTableModel)tblMapel.getModel();
        model.setRowCount(0);
        showMapel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMapel = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblKodeMatkul = new javax.swing.JLabel();
        tfKodeMatkul = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        lblNamaMatkul = new javax.swing.JLabel();
        tfNamaMatkul = new javax.swing.JTextField();

        setFocusCycleRoot(false);
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(730, 420));
        setRequestFocusEnabled(false);

        tblMapel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "KODE MATKUL", "NAMA MATKUL"
            }
        ));
        tblMapel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblMapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMapelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMapel);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add.png"))); // NOI18N
        btnAdd.setText("TAMBAH");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-making_notes.png"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete_trash.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblKodeMatkul.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKodeMatkul.setText("KODE MATKUL:");

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-reset.png"))); // NOI18N
        btnReset.setText("RESET");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblNamaMatkul.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNamaMatkul.setText("NAMA MATKUL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblKodeMatkul, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaMatkul, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfKodeMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNamaMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKodeMatkul)
                            .addComponent(tfKodeMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNamaMatkul)
                            .addComponent(tfNamaMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit)
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnReset)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMapelMouseClicked
        DefaultTableModel model = (DefaultTableModel)tblMapel.getModel();
        int i = tblMapel.getSelectedRow();
        kodeMatkul = (model.getValueAt(i, 1).toString());
        System.out.println(kodeMatkul);
        Statement st;
        ResultSet rs;
        
        String query = "SELECT * FROM " + namaTabel +" WHERE kode_matkul ="+kodeMatkul;
        try {
            st = con.createStatement();
            rs = st.executeQuery(query);
            while(rs.next()){
                kodeMatkul = (rs.getString("kode_matkul"));
                tfKodeMatkul.setText(rs.getString("kode_matkul"));
                tfNamaMatkul.setText(rs.getString("nama_matkul"));
            }
            
//            rs = st.executeQuery(query2);
            
        } catch (Exception e) {
            e.printStackTrace();
        }

//        tfNPM.setText(model.getValueAt(i, 0).toString());
//        tfNama.setText(model.getValueAt(i, 1).toString());
//        cbAngkatan.getModel().setSelectedItem(model.getValueAt(i, 2).toString());

    }//GEN-LAST:event_tblMapelMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(checkField()){
            String query = "INSERT INTO " + namaTabel +"(`kode_matkul`, `nama_matkul`)"+
                " VALUES ('"+tfKodeMatkul.getText().toUpperCase()+"', '"+Utility.capitalizeWord(tfNamaMatkul.getText())+"')";
            executeSQLQuery(query, "Inserted", 1);
        } else{
            JOptionPane.showMessageDialog(this, "Isi Semua Field!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(kodeMatkul.isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data Yang Ingin Di Edit!");
        } else{
            if(checkField()){
                int conf;
                conf = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Mengedit Data Ini?",
                    "Warning",JOptionPane.WARNING_MESSAGE);
                if(conf == 0){
                    String query = "UPDATE "+ namaTabel +" SET `kode_matkul` = '" +tfKodeMatkul.getText()+"', "+
                            "`nama_matkul` = '" +Utility.capitalizeWord(tfNamaMatkul.getText())+"' "+
                            " WHERE `kode_matkul` ="+kodeMatkul.toUpperCase();
                    executeSQLQuery(query, "Updated", 2); 
                }
            } else{
                JOptionPane.showMessageDialog(this, "Isi Semua Field!");
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(kodeMatkul.isEmpty())
         {
             JOptionPane.showMessageDialog(this, "Pilih Data Yang Ingin Di Hapus!");          
         }
         else{
            int conf;
            conf = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus Data Ini?",
                    "Warning",JOptionPane.WARNING_MESSAGE);
            if(conf == 0){
                String query = "DELETE FROM "+ namaTabel +" WHERE kode_matkul="+kodeMatkul;
                executeSQLQuery(query, "Deleted", 3);
            }
         }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tfKodeMatkul.setText("");
        tfNamaMatkul.setText("");
    }//GEN-LAST:event_btnResetActionPerformed
    
    
    public boolean checkField(){
        if(
                tfKodeMatkul.getText().trim().isEmpty() ||
                tfNamaMatkul.getText().trim().isEmpty()
                ) {
            return false;
        } else{
            return true;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKodeMatkul;
    private javax.swing.JLabel lblNamaMatkul;
    private javax.swing.JTable tblMapel;
    private javax.swing.JTextField tfKodeMatkul;
    private javax.swing.JTextField tfNamaMatkul;
    // End of variables declaration//GEN-END:variables
}
